version: "3.8"

networks:
    shared-network:
        external: true

services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: ./docker/React/Dockerfile
        volumes:
            - ./frontend:/frontend
        working_dir: /frontend
        ports:
            - 3000:3000
        tty: true
        stdin_open: true
        networks:
            - default
            - shared-network
        command: sh -c "npm install && npm start"

    backend:
        container_name: backend
        build:
            context: .
            dockerfile: ./docker/Express/Dockerfile
        volumes:
            - ./backend:/backend
        working_dir: /backend
        ports:
            - 3001:3000
        tty: true
        stdin_open: true
        networks:
            - default
            - shared-network
        command: sh -c "npm install && npm run start"
