version: "3.8"

services:
    frontend:
        container_name: frontend
        build:
            context: .
            dockerfile: ./docker/React/Dockerfile
        volumes:
            - ./frontend:/frontend
        working_dir: /frontend
        ports:
            - 3000:3000
        tty: true
        stdin_open: true
        command: sh -c "npm install && npm start"
